[package]
name = "rcheat"
version = "0.1.1"
edition = "2018"
authors = ["handy-sun <handy-sun@foxmail.com>"]
homepage = "https://github.com/handy-sun/rcheat"
repository = "https://github.com/handy-sun/rcheat"
description = "Get/modify variable's value in another Linux running process"
license = "MIT"
readme = "README.md"
keywords = ["ptrace", "elf"]
build = "build.rs"

[dependencies]
clap = { version = "4.5.0", features = ["derive", "wrap_help"] }
shadow-rs = "^0"
anyhow = "1.0.0"
bytes = "^1.7"
goblin = "0.8.0"
cpp_demangle = "0.4.4"
rustc-demangle = "0.1.*"
ansi_term = "0.12.1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", default-features = false, features = [
    "ptrace",
    "fs",
]}

[build-dependencies]
shadow-rs = "^0"
