[package]
name = "rcheat"
version = "0.0.2"
edition = "2018"
authors = ["handy-sun <handy-sun@foxmail.com>"]
description = "Cheat a running linux process' memory"
license = "MIT"
build = "build.rs"

[dependencies]
chrono = "^0.4"
nix = { version = "^0.29", features = ["ptrace", "fs"] }
clap = { version = "^4", features = ["derive", "wrap_help"] }
shadow-rs = "^0"
anyhow = "1"
bytes = "^1.7"
goblin = "^0"

[build-dependencies]
shadow-rs = "^0"
