[package]
name = "rcheat"
version = "0.1.0"
edition = "2018"
authors = ["handy-sun <handy-sun@foxmail.com>"]
homepage = "https://github.com/handy-sun/rcheat"
repository = "https://github.com/handy-sun/rcheat"
description = "Get/modify variable's value in another Linux/Unix running process"
license = "MIT"
keywords = ["ptrace", "elf"]
build = "build.rs"

[dependencies]
chrono = "^0.4"
nix = { version = "^0.29", features = ["ptrace", "fs"] }
clap = { version = "^4", features = ["derive", "wrap_help"] }
shadow-rs = "^0"
anyhow = "1"
bytes = "^1.7"
goblin = "^0"

[build-dependencies]
shadow-rs = "^0"
