name: Bug Report
description: report any bugs
title: '[Bug Report] <title>'
labels: [topic/bug]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce it (as minimally and precisely as possible).
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Do ...
        4. See error...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **Project version (use option: `--version`)**: v0.2.4
          - **OS (e.g `cat /etc/os-release`)**: Debian 12
          - **Others**: NA
      value: |
          - **Project version (use option: `--version`)**:
          - **OS (e.g `cat /etc/os-release`)**:
          - **Others**:
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Config? Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
